branch-defaults:
  default:
    environment: oxidizer
global:
  application_name: oxidizer
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2015.03 v2.0.0 running Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: null
